version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build:
    docker:
      - image: circleci/node:14.15.0-browsers
    
    working_directory: ~/repo

    steps:
      - checkout
    
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      #- run: yarn lint
    
      #- run: yarn size
    
      #- run: yarn test
    
      - run: yarn build

      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build
          to: "s3://udemy-react-authentication-bucket/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true